start_url = 'https://www.songsmp3.co/1/bollywood-music/list-'
end_url   = '.html' 
all_letters  = 'abcdefghijklmnopqrstuvwxyz'
songsMp3DomainUrl = 'https://www.songsmp3.co'
soundCloudURL	= 'https://api.soundcloud.com'
soundCloudEndUrl = '?client_id=eef823eb72081eccc8684bc619021062'
READ = "r"
WRITE = "w"
READ_AND_WRITE = "r+w"
